name: thcDoctorMobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  agora_rtc_engine: ^1.0.8
  cached_network_image: ^2.3.2+1
  cloud_firestore: ^0.14.0+2
  page_transition: ^1.1.5
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_messaging: ^7.0.3
  firebase_storage: ^4.0.0
  firebase_analytics: ^5.0.2
  flutter_rating_bar: ^3.0.1+1
  flutter_twilio_voice: ^0.0.4
  hive: ^1.4.1+1
  http: ^0.12.1
  permission_handler: 3.0.0
  google_sign_in: ^4.5.6
  shared_preferences: '>=0.5.7+3 <2.0.0'
  path_provider: ^1.6.5
  path: ^1.6.2
  provider: ^4.1.2
  google_maps_flutter: ^0.5.28+1
  dio: ^3.0.9
  loading_overlay: ^0.2.1
  fluttertoast: ^7.0.2
  image_picker: ^0.6.7+7
  uuid: ^2.2.2
  file_picker: ^2.0.0
  sms_autofill: ^1.2.6
  flutter_local_notifications: 1.4.4+4 #1.4.0
  intl: ^0.16.1
  photo_view: ^0.10.2 #0.5.0
  table_calendar: ^2.3.0
  share: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/SofiaPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SofiaPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SofiaPro-Regular.ttf
        - asset: assets/fonts/SofiaPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SofiaPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SofiaPro-BoldItalic.ttf
          weight: 700
          style: italic
